[build]

base = "apps/angular-monorepo-nx"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[plugins]]
  package = "@netlify/angular-runtime"

[context.deploy-preview]
  publish = "dist/apps/angular-monorepo-nx"
